trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(Build.ArtifactStagingDirectory)\apks'
  clientesPath: 'assets\clientes'
  apkName: 'Consorcio'

stages:
- stage: Build
  jobs:
  - job: BuildApks
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
      displayName: 'Instalar Java 11'

    - task: FlutterInstall@0
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'

    - powershell: |
        $ErrorActionPreference = 'Stop'
        Write-Host "Iniciando build para todos os clientes..."
        
        Get-ChildItem -Path "$(Build.SourcesDirectory)\$(clientesPath)" -Directory | ForEach-Object {
          $cliente = $_.Name
          $clientePath = "$(Build.SourcesDirectory)\$(clientesPath)\$cliente"
          $arquivoJks = "$(clientesPath)\$cliente\android-key\$cliente.jks"
          $apkName = "Consorcio"

          if (-Not (Test-Path -Path $arquivoJks)) {
            Write-Host "Arquivo JKS não encontrado para o cliente: $cliente. Pulando este cliente."
            return
          }

          Write-Host "Cliente: $cliente"
          Write-Host "Sobrescrevendo arquivos de configuracao..."

          Copy-Item "$clientePath\Icons\" -Destination "android\app\src\main\res\" -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item "$clientePath\dotenv" -Destination "dotenv" -Force -ErrorAction SilentlyContinue
          Copy-Item "$clientePath\dotenv" -Destination "assets\dotenv" -Force -ErrorAction SilentlyContinue
          Copy-Item "$clientePath\AndroidManifest.xml" -Destination "android\app\src\main\AndroidManifest.xml" -Force -ErrorAction SilentlyContinue
          Copy-Item "$clientePath\AndroidManifest.xml" -Destination "android\app\src\debug\AndroidManifest.xml" -Force -ErrorAction SilentlyContinue
          Copy-Item "$clientePath\build.gradle" -Destination "android\app\build.gradle" -Force -ErrorAction SilentlyContinue
          Copy-Item "$clientePath\MainActivity.kt" -Destination "android\app\src\main\kotlin\com\example\project_evydhence\MainActivity.kt" -Force -ErrorAction SilentlyContinue
          Copy-Item "$clientePath\key.properties" -Destination "android\key.properties" -Force -ErrorAction SilentlyContinue
          Copy-Item "$clientePath\images\background.png" -Destination "images\background.png" -Force -ErrorAction SilentlyContinue
          Copy-Item "$clientePath\images\icon.png" -Destination "images\icon.png" -Force -ErrorAction SilentlyContinue

          if (Test-Path -Path "android\app\src\main\kotlin\com\example\project_evydhence\MainActivity.kt") {
            Write-Host "MainActivity.kt encontrado e copiado."
          } else {
            Write-Host "MainActivity.kt não encontrado. Pulando cópia deste arquivo."
          }

          Write-Host "Limpando build anterior..."
          flutter clean

          Write-Host "Gerando APK release nao assinado..."
          flutter build apk
          Copy-Item "build\app\outputs\flutter-apk\app-release.apk" -Destination "$env:outputDirectory\$cliente$apkName-app-release.apk" -Force -ErrorAction SilentlyContinue

          Write-Host "Gerando AAB nao assinado..."
          flutter build appbundle

          # Verificação se o arquivo .aab foi gerado
          $aabPath = "build\app\outputs\bundle\release\app-release.aab"
          if (-Not (Test-Path -Path $aabPath)) {
          Write-Host "Erro: O arquivo $aabPath não foi encontrado. Verifique se o comando 'flutter build appbundle' foi executado corretamente."
          return
        }

        Write-Host "Processo de assinatura do APK..."
        $password = $cliente.ToLower()  # Converte o nome do cliente para minúsculas
        Write-Host "Keystore path: $arquivoJks"
        Write-Host "Keystore password: $password"
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore "$arquivoJks" -storepass "$password" "$aabPath" "$cliente"
        Copy-Item "$aabPath" -Destination "$env:outputDirectory\$cliente$apkName-Assinado.aab" -Force -ErrorAction SilentlyContinue
        }
      displayName: 'Build dos APKs para todos os clientes'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(outputDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish APKs'
